# Generated by Django 2.2.1 on 2019-06-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190610_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(help_text='Select a language for the book', max_length=20, null=True, verbose_name='Language'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
