# Generated by Django 2.2.1 on 2019-06-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
